### ISSUE TITLE
yarn dev throws error

### ISSUE THREAD

**Issue by byteshiva** [lukethacoder/tauri-react-example#1]
I'm getting below error when I run the dev server also the Cargo.toml settings seems to be correct for deserialize. The OS ubuntu 20.04. Am I missing something here. 

I followed 
https://serde.rs/derive.html

 ```yarn install
 yarn tauri dev
```

```
error: cannot find derive macro `Deserialize` in this scope
 --> src/cmd.rs:9:10
  |
9 | #[derive(Deserialize)]
  |          ^^^^^^^^^^^

error: cannot find attribute `serde` in this scope
  --> src/cmd.rs:10:3
   |
10 | #[serde(tag = "cmd", rename_all = "camelCase")]
   |   ^^^^^

error[E0277]: the trait bound `cmd::Cmd: serde::de::Deserialize<'_>` is not satisfied
    --> src/main.rs:17:13
     |
17   |       match serde_json::from_str(arg) {
     |             ^^^^^^^^^^^^^^^^^^^^ the trait `serde::de::Deserialize<'_>` is not implemented for `cmd::Cmd`
     | 
    ::: /home/siva/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.51/src/de.rs:2397:8
     |
2397 |     T: de::Deserialize<'a>,
     |        ------------------- required by this bound in `serde_json::de::from_str`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `app`.


```

**Comment by byteshiva** [comment]
@lukethacoder - Do you have any update for it.

**Comment by lukethacoder** [comment]
Hi @byteshiva - havn't run this repo in awhile so not surprised it is erroring out. Initially had some errors with an outdated rust version attempting to get it working.

I don't have much time at the moment to be checking out the build issues but can I suggest checking out the official [Tauri examples repo](https://github.com/tauri-apps/examples).

I originally pulled together pieces from there to build this out. It was a tad confusing because the examples are referencing a local instance of the Tauri package, instead of the published one (via cargo/npm).

Aside from the official repo it may be a version miss-match issue of some sort. Whether that's rust/npm/tauri rust package/tauri npm package. Not too sure. I would love to get back to this project eventually and get it fixed up.

**Comment by lukethacoder** [comment]
@byteshiva 

found a spare few hours this arvo to fix this one up. Not 100% sure what the issue was but the latest commit should now compile and run nicely.

Part of the issue is that Tauri has changed parts of their API. I've bumped both the NPM and cargo dependencies and made changes to the Tauri config based on the API changes. (check out the history if you want to see exactly what API changes were made).

Wouldn't be surprised if this (and many other Tauri based projects) break until Tauri is properly released. A lot of the changes are nice, but a bit of a pain in the ass to keep on top of.

**Comment by byteshiva** [comment]
It worked ! but it threw GDK Critical Error 

```
(app:12002): Gdk-CRITICAL **: 23:31:25.446: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed
CONSOLE ERROR Unhandled Promise Rejection: notification' not on the allowlist (https://tauri.studio/docs/api/config#tauri.allowlist)
http://localhost:3001/static/js/0.chunk.js:36833:18: CONSOLE LOG [HMR] Waiting for update signal from WDS...


```
